sudo: false

branches:
  except:
    - gh-pages

cache:
  directories:
      - build/dox/Utilities/Doxygen/html/
      - build/slicer-src

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
script:
    - chmod +x dox_build.sh
    - ./dox_build.sh
